repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: "v3.8.0-1"
    hooks:
      - id: shfmt # native (requires/installs Go to build)
      # - id: shfmt-docker # Docker image (requires Docker to run)

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        entry: prettier --write --ignore-unknown
        types_or: [json, yaml, markdown]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.8"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
